require 'rspec/core'
require 'rspec/core/rake_task'
require 'json'
require 'yaml'
require 'fileutils'

# Config files
intrigue_basedir = File.dirname(__FILE__)

# Configuration and scripts
puma_config_file = "#{intrigue_basedir}/config/puma.rb"
system_config_file = "#{intrigue_basedir}/config/config.json"
database_config_file = "#{intrigue_basedir}/config/database.yml"
sidekiq_interactive_config_file = "#{intrigue_basedir}/config/sidekiq-task-interactive.yml"
sidekiq_autoscheduled_config_file = "#{intrigue_basedir}/config/sidekiq-task-autoscheduled.yml"
sidekiq_app_config_file = "#{intrigue_basedir}/config/sidekiq-app.yml"
control_script = "#{intrigue_basedir}/util/control.sh"

# Data files
geolocation_database = "#{intrigue_basedir}/data/geolitecity/latest.dat"
web_accounts_list =  "#{intrigue_basedir}/data/web_accounts_list/web_accounts_list.json"

desc "Clean"
task :clean do
  puts "[+] Cleaning up!"
  FileUtils.mv  puma_config_file, "#{puma_config_file}.backup"
  FileUtils.mv  system_config_file, "#{system_config_file}.backup"
  FileUtils.mv  database_config_file, "#{database_config_file}.backup"
  FileUtils.mv  sidekiq_interactive_config_file, "#{sidekiq_interactive_config_file}.backup"
  FileUtils.mv  sidekiq_autoscheduled_config_file, "#{sidekiq_autoscheduled_config_file}.backup"
  FileUtils.mv  sidekiq_app_config_file, "#{sidekiq_app_config_file}.backup"
  FileUtils.mv  geolocation_database, "#{geolocation_database}.backup"
  FileUtils.mv  web_accounts_list, "#{web_accounts_list}.backup"
end

desc "System Setup"
task :setup do

  puts "[+] Setup initiated!"

  autogenerated_system_pass = "#{(0...16).map { ('a'..'z').to_a[rand(26)] }.join}"
  puts "[+] Generating system password: #{autogenerated_system_pass}"

  ## Copy puma config into place
  puts "[+] Copying puma config...."
  if File.exist? puma_config_file
    puts "File already exists, skipping: #{puma_config_file}"
  else
    puts "Creating.... #{puma_config_file}"
    FileUtils.cp "#{puma_config_file}.default", puma_config_file
  end

  ## Copy system config into place
  puts "[+] Copying system config...."
  if File.exist? system_config_file
    puts "File already exists, skipping: #{system_config_file}"
  else
    puts "Creating.... #{system_config_file}"
    FileUtils.cp "#{system_config_file}.default", system_config_file

    # Set up our password
    config = JSON.parse(File.read(system_config_file))
    config["credentials"]["password"] = autogenerated_system_pass
    File.open(system_config_file,"w").puts JSON.pretty_generate(config)
  end

  ## Copy database config into place
  puts "[+] Copying database config...."
  if File.exist? database_config_file
    puts "File already exists, skipping: #{database_config_file}"

  else
    puts "[+] Creating.... #{database_config_file}"
    FileUtils.cp "#{database_config_file}.default", database_config_file

    # Set up our password
    config = YAML.load_file(database_config_file)
    config["development"]["password"] = autogenerated_system_pass
    config["production"]["password"] = autogenerated_system_pass
    config["docker"]["password"] = autogenerated_system_pass
    File.open(database_config_file,"w").puts YAML.dump config
  end

  ## Copy sidekiq task worker config into place
  puts "[+] Setting up task worker config...."
  if File.exist? sidekiq_interactive_config_file && sidekiq_autoscheduled_config_file && sidekiq_app_config_file
    puts "File already exists, skipping: #{sidekiq_interactive_config_file}"
    puts "File already exists, skipping: #{sidekiq_autoscheduled_config_file}"
    puts "File already exists, skipping: #{sidekiq_app_config_file}"
  else
    puts "Copying: #{sidekiq_interactive_config_file}.default"
    puts "Copying: #{sidekiq_autoscheduled_config_file}.default"
    puts "Copying: #{sidekiq_app_config_file}.default"
    FileUtils.cp "#{sidekiq_interactive_config_file}.default", sidekiq_interactive_config_file
    FileUtils.cp "#{sidekiq_autoscheduled_config_file}.default", sidekiq_autoscheduled_config_file
    FileUtils.cp "#{sidekiq_app_config_file}.default", sidekiq_app_config_file
  end

  puts "[+] Obtaining latest data..."
  unless File.exist? geolocation_database && web_accounts_list
    puts "Getting data files (will fail if we don't have internet)"
    Dir.chdir("#{intrigue_basedir}/data/"){ puts %x["./get_latest.sh"] }
  end

  ## Copy control script
  puts "[+] Copying control script..."
  if File.exist? control_script
    puts "File already exists, skipping: #{control_script}"
  else
    puts "Creating.... #{control_script}"
    FileUtils.cp "#{control_script}.default", control_script

    # Configure the IDIR directory
    script_text = File.read(control_script)
    new_script_text = script.gsub("IDIR=/path/to/install/directory","IDIR=#{intrigue_basedir}")
    File.open(control_script,"w").puts new_script_text

    # Make a link if
    if Dir.exist? "/etc/init.d"
      puts 'Creating system-level startup script'
      `ln -s #{intrigue_basedir}/util/control.sh /etc/init.d/intrigue`
    end

  end

end

desc "Run Database Migrations"
task :migrate => :setup do

  puts "[+] Running Database Migrations"

  begin
    require 'yaml'
    require 'json'
    require 'dm-core'
    require 'dm-migrations'
    require 'dm-validations'
    require 'dm-types'

    intrigue_basedir = File.dirname(__FILE__)
    config_file = "#{intrigue_basedir}/config/config.json"

    begin
      system_config = JSON.parse File.read(config_file)
    rescue JSON::ParserError => e
      puts "Fatal! Unable to read #{config_file}"
      return
    end

    database_config = YAML.load_file("#{intrigue_basedir}/config/database.yml")
    database_environment = ENV.fetch('INTRIGUE_ENV', "development")

    unless database_config[database_environment]
      puts "FATAL! Unable to read database configuration"
      return
    end

    Dir["#{intrigue_basedir}/app/models/*.rb"].each { |file| require_relative file }

    # Run our setup with the correct enviroment
    DataMapper::Logger.new($stdout, :debug)
    DataMapper.setup(:default, database_config[database_environment])
    DataMapper.auto_upgrade!
    DataMapper.finalize

    puts "Creating default project..."
    Intrigue::Model::Project.create(:name => "Default") unless Intrigue::Model::Project.first

  rescue Exception => e
    puts "Error... Unable to migrate: #{e}"
  end
end

desc "Reset Workers"
task :reset_workers do
  puts "[+] Resetting workers"
  require './core'
  Intrigue::Model::Project.all.each do |p|
    puts "Clean state for #{p.name}"
    p.graph_generation_in_progress=false
    p.save
  end
end

desc "Run Specs"
task :spec do
end

desc "Run Integration Specs (requires API running)"
task :integration do
  t.rspec_opts = "--pattern spec/integration/*_spec.rb"
end
